### ISSUE TITLE
Getting invoice rows from merged orders.

### ISSUE THREAD

**Issue by eivl** [loyning/python-24so#12]
I have a merged order that I want to lookup the content of each row.

`api.invoice.from_ordreids(order_number)` does not provide enough information, it has `Price` and `TaxSettings` but nothing more. 

`api.invoice.from_invoiceids(invoice_id)` looks more on par just by name, but it gives me this error. 

```py
>>> api.invoice.from_invoiceids(117708)

ERROR:suds.client:<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://24sevenOffice.com/webservices" xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header/>
   <ns1:Body>
      <ns0:GetInvoices>
         <ns0:searchParams>
            <ns0:InvoiceIds>117708</ns0:InvoiceIds>
         </ns0:searchParams>
      </ns0:GetInvoices>
   </ns1:Body>
</SOAP-ENV:Envelope>
>>> api.invoice.from_invoiceids(117708)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    api.invoice.from_invoiceids(117708)
  File "/home/eivl/PycharmProjects/24sevenofficeAPI/tfsoffice/resources/invoice.py", line 101, in from_invoiceids
    return self._client._get_collection(method, params, **options)
  File "/home/eivl/PycharmProjects/24sevenofficeAPI/tfsoffice/client.py", line 276, in _get_collection
    raise exceptions.WebFault(
tfsoffice.exceptions.WebFault: Server was unable to process request. ---> Please specify at least one search parameter.
>>> 
```
What are the wanted search parameters needed? 

I would like to get these parameters from each row:
Product no. Name, Quantiry, Price, Discound, Sum

![link to rows](https://i.imgur.com/E1lP44W.png)

**Comment by eivl** [comment]
do you know how to advise me about this @loyning?
